### ISSUE TITLE
Writing wasm tooling in Rust

### ISSUE THREAD

**Issue by aturon** [rustwasm/team#10]
This issue tracks existing and potential wasm tooling opportunities for Rust.

One of the exciting things about the wasm space is that there's a lot of need for brand new systems code to be written in the tooling space, e.g. code to munge .wasm files. A lot of the early tooling has been written in C++, but there's a real opportunity for Rust to serve as a common language both for writing wasm tools *and* for producing wasm code.

# Existing wasm tools written in Rust

- [wasm-gc](https://github.com/alexcrichton/wasm-gc), "a small command to gc a wasm module and remove all unneeded exports, imports, functions, etc."
- [wasm-nm](https://github.com/fitzgen/wasm-nm), "list the symbols within a wasm file".
- [wasm-snip](https://github.com/fitzgen/wasm-snip), "replaces a wasm function body with `unreachable`"
- [rustwasm](https://github.com/joshuawarner32/rust-wasm), a wasm interpreter in Rust
- [wasmi](https://github.com/pepyakin/wasmi), wasm interpreter in Rust,
- [parity-wasm](https://github.com/paritytech/parity-wasm), wasm (de)serialization in Rust,
- [wasmparser](https://github.com/yurydelendik/wasmparser.rs) - a wasm binary decoder with optional validation, in Rust
 - [wasmtext](https://github.com/yurydelendik/wasmtext) - prints wasm modules in text format, in Rust
 - [wasmstandalone](https://github.com/sunfishcode/wasmstandalone) - standalone JIT-based wasm runner, in Rust, using Cretonne, in early development

# Desired wasm tools that could be written in Rust

- [wasm size profiler](https://github.com/aturon/rust-wasm/issues/20)

# Possible RIIR opportunities

Here are some existing tools that could, in principle, be (re)written in Rust instead:

- The [wabt tools](https://github.com/WebAssembly/wabt)
- Tools for the [ewasm project](https://github.com/ewasm)

**Comment by aturon** [comment]
A good example here is @alexcrichton's [wasm-gc](https://github.com/alexcrichton/wasm-gc).

What are some other existing Rust-based tools we know about? And what are some needed tools we could start writing Rust code for?

**Comment by fitzgen** [comment]
https://github.com/fitzgen/wasm-nm

https://github.com/fitzgen/wasm-snip

**Comment by aturon** [comment]
- [A wasm interpreter in Rust](https://github.com/joshuawarner32/rust-wasm)
- [wasm serialization in Rust](https://github.com/paritytech/parity-wasm)

**Comment by aturon** [comment]
Added some RIIR (rather than WIIR) opportunities to the issue. This is more to inspire ideas for additional tools, rather than to suggest RIIR today.

**Comment by sunfishcode** [comment]
More existing projects:
 - [wasmparser](https://github.com/yurydelendik/wasmparser.rs) - a wasm binary decoder with optional validation, in Rust
 - [wasmtext](https://github.com/yurydelendik/wasmtext) - prints wasm modules in text format, in Rust
 - [wasmstandalone](https://github.com/sunfishcode/wasmstandalone) - standalone JIT-based wasm runner, in Rust, using Cretonne, in early development

**Comment by pepyakin** [comment]
btw parity-wasm also contains an interpreter.

**Comment by pepyakin** [comment]
- [binaryen-rs](https://github.com/pepyakin/binaryen-rs) - bindings for Binaryen. 
- [wabt-rs](https://github.com/pepyakin/wabt-rs) — bindings for WABT, particularly wat2wasm and wasm2wat,

**Comment by pepyakin** [comment]
ah i see, WIIR - write it in rust

**Comment by aturon** [comment]
@pepyakin thanks, clarified both.

**Comment by pepyakin** [comment]
Recently I spent a looot of time in wast code generated by Rust+emcc+fastcomp/Rust+emcc+llvm and recently with unknown-unknown. I think it would be cool if I have had something like a decompiler for WASM.

**Comment by alexcrichton** [comment]
From my experience parity-wasm has solved all problems for parsing/encoding a wasm module, but I think it'd also be slick to have a crate 100% dedicated to just that (in that parity-wasm also has an interpreter).

**Comment by mgattozzi** [comment]
Looks like somebody is working on wabt bindings in rust as well:
https://github.com/pepyakin/wabt-rs

**Comment by pepyakin** [comment]
@alexcrichton there was some discussions about splitting interpreter into a separate crate. I actually like the idea.

**Comment by pepyakin** [comment]
Yep, actual split of interpreter took place: https://github.com/pepyakin/wasmi
It has quite a few differences from [parity-wasm](https://github.com/paritytech/parity-wasm) version.

**Comment by spastorino** [comment]
I'm interested in helping here, will ping sbdy on IRC :).

**Comment by alexcrichton** [comment]
We've made a lot of progress here and I think we've reached a good steady state, so closing.
