### ISSUE TITLE
Nail down relationship to hellorust.com

### ISSUE THREAD

**Issue by aturon** [rustwasm/team#11]
The http://www.hellorust.com/ site is at attempt to gather news and resources related to Rust and wasm. Right now, this repo points to a handful of pages there.

It'd be good to pin down the roles for each, and ensure that between the two we can keep exhaustive early tracking of e.g. Rust-to-wasm projects.

**Comment by aturon** [comment]
cc @badboy

**Comment by steveklabnik** [comment]
I also have the still-unannounced-becuase-I-never-finished-it https://www.steveklabnik.com/wasm/

**Comment by aturon** [comment]
So for my part, my goal with this repo is largely to coordinate "bleeding edge" efforts -- have a place where we can record discoveries and experiences, and map out vision and implementation work together.

That's as opposed to a "user facing" resource that's more polished and all about a streamlined "here's how you use Rust + wasm" story.

Sort of an "interals" vs "users" distinction, if you will. But in these early days, there's not much of a difference :-)

**Comment by aturon** [comment]
That said, I am also totally open to consolidating more user-facing materials here. For example, @steveklabnik, you'd be more than welcome to start a `faq.md` bringing in the material you'd written.

**Comment by steveklabnik** [comment]
Yeah; my goal with the above is to create a WASM resource, that happens to use Rust, rather than a Rust resource about wasm. Vaguely related, but slightly different!

**Comment by badboy** [comment]
hellorust.com gives us the opportunity to give us working examples with little overhead. I’d be happy to migrate some of the documentation happening here and give more people push access to it. (hellorust.com is currently handled by my server, proxying requests to www2.hellorust.com in order to handle TLS)

**Comment by alexcrichton** [comment]
While this didn't quite happen I think we're in an alright place today, so closing.
