### ISSUE TITLE
should we move this over to the rustwasm org?

### ISSUE THREAD

**Issue by ashleygwilliams** [rustwasm/team#110]
i'd recommend moving it and renaming the repo to "team" cc @fitzgen

**Comment by fitzgen** [comment]
Or maybe "book"?

**Comment by ashleygwilliams** [comment]
@fitzgen book sounds good to me, tho the issues people ask on here seem better suited to a "general" or "team" repo. i'm down for either, or both, or really whatever, just think its confusing to have this here and not in the other org :)

**Comment by mgattozzi** [comment]
Well the content of the repo is the book and information but the issues themselves are more coordination of the team, so I'm hesitant to call it "book". It might be better to split it out into a separate repo then and move this and call it team to retain the issue tracker.

**Comment by ashleygwilliams** [comment]
yeah i think that's probably the best course of action @mgattozzi

**Comment by fitzgen** [comment]
> Well the content of the repo is the book and information but the issues themselves are more coordination of the team, so I'm hesitant to call it "book". It might be better to split it out into a separate repo then and move this and call it team to retain the issue tracker.

I am going to do this now.

**Comment by fitzgen** [comment]
There is now https://github.com/rustwasm/book and I am working on fixing the auto deploy to gh-pages.

**Comment by mgattozzi** [comment]
It's a bit late now but this is gonna really hurt SEO probably now that I think about it and we'll need to fix all kinds of links to the book.

**Comment by fitzgen** [comment]
Moved this repo to rustwasm/team.

There used to be redirects from rust-lang-nursery/rut-wasm's gh page to rustwasm/rust-wasm's gh page, but apparently that redirect doesn't survive a transer and rename combination :(

**Comment by fitzgen** [comment]
As for issues and the repo home page, they do get redirected properly.

**Comment by fitzgen** [comment]
Made an empty repo at rust-lang-nursery/rust-wasm whose gh-pages redirects to the new book URL, rustwasm.github.io/book. Unfortunately, this means that all the old issues links are 404ing instead of redirecting now :(

**Comment by fitzgen** [comment]
FWIW, I think this is the right trade off, but this is all a bit unfortunate.
