### ISSUE TITLE
[game-of-life tutorial] use a std::fmt::Display impl to render to a <pre> before using canvas

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#113]
This is a nice intermediate step between jumping all the way into exposing raw wasm memory to JS. Makes the difficulty increase smoother.

As suggested by @killercup in https://github.com/rust-lang-nursery/rust-wasm/pull/111#discussion_r180518268

**Comment by migerh** [comment]
I think this is already implemented with #121.

**Comment by killercup** [comment]
Yep!
