### ISSUE TITLE
Getting Started reference to `wasm-opt` could be more clear.

### ISSUE THREAD

**Issue by cldershem** [rustwasm/team#125]
In [Getting Started](https://github.com/rust-lang-nursery/rust-wasm/blob/master/src/setup.md) the sentence mentioning `wasm-opt` is a little confusing. It states that in some circumstances one might want to install `wasm-opt` from the `binaryen` toolkit, but doesn't say how one does that. Even after clicking through to the toolkit's own `README` it isn't clear how to install the package.

I'm sure if I took sometime I could potentially figure this out by installing `binaryen`, but that looks to be a commitment since that involves compiling from source. Since this book is possibly the first substantial intro to Rust & Wasm someone might have, it would be good to keep the barrier of entry as low as possible. A little more of an explanation that this is advanced usage or leaving that as a footnote to move to a later section of the book might help make it less of an issue.

**Comment by fitzgen** [comment]
Once you clone `binaryen`, this should do the trick:

```
cmake . && make && sudo make install
```

I think we can send a pull request their way to make it more clear / frontpage how to install their tools.

I'm it makes sense to re-host/duplicate the build instructions in our book, though.

**Comment by cldershem** [comment]
@fitzgen I think the fix depends on the target audience of the book, which I may not be 100% clear on (apologies if I overlooked them somewhere).

There are a lot of people looking at Wasm that aren't from a Systems background or even a compiled language background (ie JS or Python devs). There is a very good chance they don't have `cmake` setup, especially if they're in a Windows environment. Rust and Wasm are both kind of en vogue at the moment and therefore it is easy for someone interested in Wasm to only have `rustc` setup because they're trying Wasm for the first time with Rust. If the target audience is an "intro to using Rust and Wasm together" that can mean one thing, however, if the book is "definitive guide for using Rust and Wasm together" it can be something else.

Either way, I agree about sending a PR their way and duplicating the instructions in this book is a good step in the right direction.

**Comment by jrichocean** [comment]
This issue has been moved [here](https://github.com/rustwasm/book/issues/18)
