### ISSUE TITLE
Add a wasm-bindgen hello world to the book

### ISSUE THREAD

**Issue by johnthagen** [rustwasm/team#127]
I found Alex's blog post on wasm-bindgen to be extremely enlightening: https://hacks.mozilla.org/2018/04/javascript-to-rust-and-back-again-a-wasm-bindgen-tale/

Could something along these lines be brought into the book, perhaps even in hello world style? It seems like the next step after learning how to expose C ABI functions like those in the current hello world example.

If this was brought into the book, it could be maintained as the ecosystem evolves.

The stuff he describes in his blog seems simpler than jumping straight to Conway's Game of Life.

**Comment by adityac8** [comment]
Hey @mgattozzi Can we work together on this issue 😸

**Comment by mgattozzi** [comment]
@adityac8 I don't have time to do direct mentoring but I can write up mentoring instructions for you.

**Comment by jrichocean** [comment]
This issue has been moved [here](https://github.com/rustwasm/book/issues/16)
