### ISSUE TITLE
Vision: rust/wasm in a rust/native host

### ISSUE THREAD

**Issue by Kimundi** [rustwasm/team#14]
One of the intended use cases of WebAssembly is [non-web embeddings](http://webassembly.org/docs/non-web/). For Rust, this means that we could provide optimized libraries and tooling for running rust/wasm in a rust/native host.

The primary idea here would be to have a safe, sandboxed alternative to dynamically loaded libraries for extending functionality of a existing host process. For example:
- Extending a trusted program with untrusted user or web code.
- Alternative to scripting languages in, eg, game engines.

Ideally we could provide a set of tools similar to (or merged with) https://github.com/alexcrichton/wasm-bindgen, but optimized for a Rust host. Eg, it should be trivial to have the wasm side export an arbitrary* Rust function, and have the host side call it with arbitrary* Rust arguments by automatically adapting the interface between the different platforms.

> *: Mostly arbitrary - there would likely be a class of types that just can not be sensibly be mapped to the wasm platform and back.

This could involve defining some kind of cross-platform higher-level ABI than the C one for passing objects between wasm client and native host efficiently:
- Passing types with known identical layout like the integer types directly.
- Generating wrapper types as needed.
- Efficiently (de-)serializing data structures across the native/wasm boundary.
- Trying to reduce copy overhead by directly writing into wasm memory, or mapping host data into parts of the wasm linear memory.

A complex example of what might become possible:

Native:
```rust
let lib = load_wasm("[...].wasm");
let wasm_collect = wasm_import! (from lib: fn wasm_collect(Box<Iterator<Item=String>>));
let vec = vec!["a".to_string(), "b".to_string()];
wasm_collect.call(Box::new(vec.clone().into_iter()));
```

Wasm:
```rust

#[wasm_export]
pub fn wasm_collect(iter: Box<Iterator<Item=String>>) {
    for x in iter {
        // ...
    }
}
```

The call in this example could work like this:
- The host gets passed the Box.
- The host associates the Box with a "host heap" address.
- The host generates wrapper functions inside the wasm module for each entry in the trait's vtable that get passed such a address. It uses that address to map back to the actual host object, and delegate the calls to it.
- The client generates a trait object that delegates each method to the wrapper functions defined by the host.
- The client-side`iter` is now a regular trait object that can get called.

**Comment by aidanhs** [comment]
I've had some thoughts on this and plans in this direction. Some other notes on use-cases:
 - receive 'closures' via TCP from untrusted parties
 - allow users to submit untrusted code to a webservice which execute it over a dataset etc
 - allow users to write user defined functions (e.g. for a database) in any language they like that can be guaranteed to not crash host

**Comment by alexcrichton** [comment]
Over time we've ended up scoping the working group to primarily web-focused aspects, so I'm going to close this.
