### ISSUE TITLE
Update wasm-pack tutorial paths

### ISSUE THREAD

**Issue by mgattozzi** [rustwasm/team#154]
We're just waiting for a 0.2 release of wasm-pack right now for this issue. In https://github.com/rust-lang-nursery/rust-wasm/pull/151 we changed a path reference from `./node_modules/@MYSCOPE/wasm-add/wasm_add.js` to `@MYSCOPE/wasm-add/wasm_add.js`. As was noted in #151 after https://github.com/ashleygwilliams/wasm-pack/issues/94 is closed we can shorten this further to `@MYSCOPE/wasm-add` which is more idiomatic for JS.

Mentoring instructions:
1) In `src/wasm-pack/run-the-code.md` change the import statement of `index.js` to the above statement.
2) Test that the changes work as part of the tutorial with the new syntax

**Comment by adityac8** [comment]
Hey @mgattozzi I have gone through [ashleygwilliams/wasm-pack](https://github.com/ashleygwilliams/wasm-pack) and found that `0.2` was released. 😃

**Comment by mgattozzi** [comment]
Hey @adityac8 thanks for reminding me. This should be good to go now :D

**Comment by jrichocean** [comment]
This issue has been moved [here](https://github.com/rustwasm/book/issues/15)
