### ISSUE TITLE
Nail down management procedures around wasm32-unknown-unknown

### ISSUE THREAD

**Issue by aturon** [rustwasm/team#17]
The `wasm32-unknown-unknown` target landed, and continues to evolve, in an unofficial manner. 

On the one hand, that's good: we're not ready for a full-blown RFC process, as things are still very fast moving and we're nowhere close to making stability guarantees.

On the other hand, that makes it hard to know as a community how to make decisions about the target. And some weighty decisions are already coming up.

We should put together a rough "working group" of folks interested in both setting the vision for, and actively maintaining, the target -- and figure out a clear place to hold discussions and reach decisions.

**Comment by aturon** [comment]
If you're interested in being part of such a working group, please say so here!

**Comment by mgattozzi** [comment]
Count me in. I didn't write the `Rust and the case for wasm in 2018` post for no reason.

**Comment by koute** [comment]
I'm also definitely interested in this!

**Comment by est31** [comment]
I'm interested as well.

**Comment by pepyakin** [comment]
I'm in!

**Comment by Diggsey** [comment]
Me too!

**Comment by fitzgen** [comment]
Me as well.

**Comment by steveklabnik** [comment]
checking in

**Comment by Pauan** [comment]
I am very interested in Wasm (and JavaScript) integration for Rust, so I'm interested as well.

However, most of my expertise is with JavaScript, so I don't think I'll be able to contribute much on the Rust side of things.

**Comment by aidanhs** [comment]
Interested.

**Comment by badboy** [comment]
@aturon Please add me to that group as well, I'd like to follow this stuff and give input where I can as well

**Comment by NikVolf** [comment]
count me in

**Comment by CryZe** [comment]
I'd like to be added to that group as well. I've been working with the emscripten target since october 2016 and have quite a large project using it by now. So I'd like to help guide the native target towards something I can eventually move it to :)

**Comment by alexcrichton** [comment]
I think we've defacto figured this out since this was opened with the working group, so closing.
