### ISSUE TITLE
wasm-pack tutorial out of date

### ISSUE THREAD

**Issue by mgattozzi** [rustwasm/team#174]
This was brought up in the example repo and the code has been updated there but we need to also update the code in the tutorial here.

https://github.com/mgattozzi/wasm-add/issues/1#issuecomment-388124867

@adityac8 said they would do this and update the book here.

**Comment by adityac8** [comment]
I'm on it!

**Comment by jrichocean** [comment]
This issue has been moved [here](https://github.com/rustwasm/book/issues/14)
