### ISSUE TITLE
Request: Elaboration on MIME type and instantiateStreaming

### ISSUE THREAD

**Issue by David-OConnor** [rustwasm/team#181]
I recommend providing an example on how to accomplish the following, from the HelloWorld page:
"Note: To run with instantiateStreaming and compileStreaming, you need your webserver to serve .wasm file with application/wasm MIME type. The https crate can be used to serve files from localhost, and includes the application/wasm MIME type out of the box."
Discovering how to due this has been remarkably difficult.

**Comment by alexcrichton** [comment]
Support for mostly this is now in wasm-bindgen so I think we're good to go on this point!
