### ISSUE TITLE
emscripten targets still require no_main + binary crate

### ISSUE THREAD

**Issue by CryZe** [rustwasm/team#185]
The emscripten targets effectively still require you to create a main.rs with no_main to compile the crate as a library. This is causing a lot of problems for me as this is mostly incompatible with a normal lib.rs that you would use for other targets. This means I can't really use the same lib.rs for all the targets and instead need to hack something together to be able to compile on emscripten targets as well.

Considering emscripten still is the only feasible fallback for supporting older browsers, this is something that should be fixed.

**Comment by alexcrichton** [comment]
I think over time the wasm working group has settled on "emscripten isn't in our scope", so I'm going to close this
