### ISSUE TITLE
Migrate book issues to rustwasm/book

### ISSUE THREAD

**Issue by mgattozzi** [rustwasm/team#197]
**This is an issue reserved for people who have never contributed to the rustwasm org**

We have a bunch of issues labeled `book` on this repo. We don't want that anymore since the book now lives in [rustwasm/book][book]. If we could get the issues that are open here moved over there that would be super helpful!

Instructions:

1. Look for issues labeled `book` in this repo
2. Open up a new issue on the [rustwasm/book][book] repo
3. In that issue give it the same title as the issue you are referencing, directly link to the issue here on this repo, and copy the text of the issue over and reference the user who opened the issue with @ syntax
4. Do this for all the issues labeled book until all of them have been ported over.

As issues get opened up on the book repo I'll close the corresponding issues here! This isn't a terribly hard task, but one that would be greatly appreciated in helping to maintain the repo :D
 
[book]: https://github.com/rustwasm/book

**Comment by jrichocean** [comment]
I can jump on this

**Comment by jrichocean** [comment]
@mgattozzi I believe I have all issues ported, if there are any changes needed to the basic ported issue structure let me know & I can change them!

**Comment by mgattozzi** [comment]
@jrichocean this is exactly what I had in mind! :D Thank you so so much for taking the time to migrate all of the issues over it'll definitely help me and the book team out having them all centralized. You even updated the README which I didn't think about so thank you!
