### ISSUE TITLE
Need to figure out which video call service to use for meetings

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#201]
Google Hangouts is maxing out at 10, and we have more people who want to participate than that. Additionally, it is laggy and flaky.

appear.in seems like a possibility if we got a paid account. It has the advantage of not requiring any downloads.

Zoom  is another possibility. It has a reputation for reliability. Also requires a paid account. Requires downloading their client.

Thoughts? Other alternatives?

**Comment by sendilkumarn** [comment]
appear.in maxes out at 12 even for the paid account https://appear.in/information/pricing/

**Comment by fitzgen** [comment]
That's a bummer.

**Comment by data-pup** [comment]
If group size is an issue, would separate meetings about different projects make sense? Not sure if that would introduce more complexity, but it could help keep meetings smaller :)

**Comment by ashleygwilliams** [comment]
so- a few things here:

1. zoom has a 25 max on it's paid account tier (which i have), also allows recording and "observing" roles (see Webinars https://support.zoom.us/hc/en-us/articles/360000252726-Roles-in-a-Webinar)
2. we should figure out if we have too many people who want to actively participate before breaking into smaller meetings. it may be that folks would be happy just in an observer role (or to watch a video later). alternatively, if we have a lot of folks that want to participate, i'd be curious to see what the category breakdown of the participation interest is to see what sorts of meetings folks want, and make sure they are aligned with the working group's goals for the 2018 edition.

**Comment by sendilkumarn** [comment]
Breaking down means we need to sync and I think that will have its own issues. 

If zoom allows 25, we can try with that.

I do feel sometimes after you choose to be an observer, if you may have 1 or 2 questions you have to wait till next meeting to talk or things go offline or missed out.

**Comment by OvermindDL1** [comment]
For note, google hangouts on a paid account maxes out at 50 active video streams (and unlimited viewers), where unpaid/free account maxes out at 10 active video streams (and still unlimited viewers).

**Comment by ashleygwilliams** [comment]
my experience with large paid google hangouts has not been as good as yours @OvermindDL1 :/ every org or company i've worked at has switched due primarily to sound quality issues, even for small meetings, even on paid accounts. (just sharing my experience)

**Comment by mgattozzi** [comment]
zoom's advantage at recording stuff seems like a boon to me for meeting notes and people who want to stay on top of things but might not be able to make it. I'm in favor of it. Worse comes to worse we go to an irc meeting

**Comment by fitzgen** [comment]
Ok, let's try Zoom for the next meeting, and if it doesn't work out, we can reopen this issue.
