### ISSUE TITLE
Should we change our meeting schedule?

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#203]
I think it would be useful to meet weekly rather than every other week. I feel like every other week gives us enough time to slip out of sync with regards to what is being implemented by which thing, why, and how far along it is.

Additionally, multiple folks have stated that the current time slot (9am pacific) is not great for them, and it would be easier if we pushed it back an hour.

Thoughts?

+cc @rustwasm/core @rustwasm/book @rustwasm/wasm-pack

**Comment by data-pup** [comment]
I'd be happy to meet weekly, and pushing it back an hour would be fine with me too :)

**Comment by ashleygwilliams** [comment]
for when folks are in europe (which i often am, but not entirely) i think it might be easier to push it... forward? it may be that we need to alternate times to accommodate timezone shenanigans- do we have a sense of the timezone spread of our group?

**Comment by sendilkumarn** [comment]
+1 for hourly meeting
time change I think it will be too late for folks from Europe. But I am fine with that.

**Comment by ashleygwilliams** [comment]
i'm not as fine with the time change being too late for europe- i think a fair amount of our active contribs are from/in europe, or there often, so i would like to try to accommodate that.

**Comment by mgattozzi** [comment]
Even a half hour would be enough for me to avoid issues with my standup, but I know if we push too far back we'll make it harder for Europe. There's also the possibility of doing it an hour earlier but if you live on the west coast that's 8am so that's not ideal either. Maybe we can do another doodle for those who have an active stake in the timing? I also think we should be recording these meetings going forward. I'm not sure how I feel about weekly meetings but I'm not opposed to it.

**Comment by fitzgen** [comment]
Please fill out this doodle to see what times work out for all of us: https://doodle.com/poll/aehgrbn649us7mai

Assume this is a weekly meeting, despite the date being fixed in the doodle.

**Comment by xtuc** [comment]
Could we extend more dates on the friday 6?

**Comment by fitzgen** [comment]
> Could we extend more dates on the friday 6?

I was assuming we would continue to meet on Thursdays, and added the 24 hours of pacific time Thursday to the doodle. I think we should try and keep meeting on Thursdays, and if we can't find a good time, we can expand the doodle to more days.

**Comment by fitzgen** [comment]
Everyone who hasn't filled out the doodle yet: you have until tomorrow before I choose the new meeting time based on the answers people have filled in :)

**Comment by xtuc** [comment]
I added my preferences but I probably won't be available for this one.

**Comment by fitzgen** [comment]
The two time slots that have the most votes are 9am pacific (our current time) and 10am pacific (one hour later).

Although @mgattozzi didn't fill out the doodle, they did indicate that the existing time conflicts for them, and that pushing it back would resolve the conflict. Therefore, I am going to break the tie with that info, and settle on the 10am pacific time slot.
