### ISSUE TITLE
Multithreading Support?

### ISSUE THREAD

**Issue by Kwarrtz** [rustwasm/team#208]
Although the https://github.com/WebAssembly/threads proposal is still technically only in planning stage, it already has experimental support on Chrome and Safari (see [here](https://www.chromestatus.com/feature/5724132452859904)). It'd be great to see `std::thread` implemented on one or both of the rust wasm targets by taking advantage of this.

**Comment by fitzgen** [comment]
Because setting up the shared memory requires interop with the host, and `wasm32-unknown-unknown` is completely host-agnostic, I think we would need a new target to get `std::thread` working.

Alternatively, one could use `stdweb` or `wasm-bindgen` to get non-`std` threading working right now.

**Comment by sendilkumarn** [comment]
Thanks for bringing this up @Kwarrtz 👍 

> I think we would need a new target to get std::thread working.

May be I am totally wrong ( I haven't played that much with `wasm32-u-u`'s architecture), cant this be included by default (or atleast via a flag) in `wasm32-unknown-unknown` since we just need to call a few atomic functions (like `wake`, `wait`) 

> Alternatively, one could use stdweb or wasm-bindgen to get non-std threading working right now.

I think this should be documented somewhere to highlight users about this.

**Comment by Kwarrtz** [comment]
@fitzgen What about `wasm32-unknown-emscripten` then?

**Comment by fitzgen** [comment]
I am less familiar with emscripten; I don't know if rustc vendors an old version that would need to be updated or what.

**Comment by Kwarrtz** [comment]
From https://github.com/kripken/emscripten/wiki/Pthreads-with-WebAssembly: "Emscripten now also has experimental support for the wasm threading spec. Currently you need to use the head of the incoming branch of emscripten."

**Comment by alexcrichton** [comment]
https://rustwasm.github.io/2018/10/24/multithreading-rust-and-wasm.html shows the "state of the art" in wasm-bindgen and we're working on pushing on that wherever possible, so I'm going to close this
