### ISSUE TITLE
Replace rust-lang-nursery/rust-wasm links in issues

### ISSUE THREAD

**Issue by Alexendoo** [rustwasm/team#212]
Issues can be helpful to search through when you have questions that may not be relevant to the main written documentation, but there are a few broken links still knocking about the rustwasm repos that point to the old repository at https://github.com/rust-lang-nursery/rust-wasm.

I can't think of an easy way to find/replace them since it's difficult to find them all in github's search, which probably leaves it as either a manual process or writing a script for GitHub's API

e.g. in #82

**Comment by alexcrichton** [comment]
I think we'll definitely do this as they pop up but otherwise this problem should solve itself in time!
