### ISSUE TITLE
rust-lld not found

### ISSUE THREAD

**Issue by Rillian-Grant** [rustwasm/team#215]
## I followed the instructions on page 4 of the book but when I got to the compilation stage I encounterd an error:

```
pi:~/Documents/Programming/Rust/wasm/Hello_World/hello-world $ cargo build --target wasm32-unknown-unknown --release
   Compiling hello-world v0.1.0 (file:///home/pi/Documents/Programming/Rust/wasm/Hello_World/hello-world)
error: linker `rust-lld` not found                                       ] 0/1  
  |
  = note: No such file or directory (os error 2)

error: aborting due to previous error

error: Could not compile `hello-world`.                                         

To learn more, run the command again with --verbose.
```

# I am using a RPi 3B+ with Debain Stretch.

**Comment by alexcrichton** [comment]
Thanks for the report! I think this'll be an issue for upstream rust-lang/rust, right now we only produce `rust-lld` on "tier 1" platforms, so we don't distribute a precompiled binary for your platform. You'll need to compile and install LLD manually to use it on ARM

**Comment by Rillian-Grant** [comment]
How do I do that?

**Comment by alexcrichton** [comment]
I believe LLD [should have documentation](https://lld.llvm.org/getting_started.html)

**Comment by Rillian-Grant** [comment]
Thanks
