### ISSUE TITLE
Use case: executable app bundles

### ISSUE THREAD

**Issue by isiahmeadows** [rustwasm/team#224]
I've been privately exploring the concept of using WebAssembly modules for app bundles, with a few custom sections for static assets, metadata, etc. The primary idea here is to:

- Provide a platform where I don't have to roll much tooling at all to make it work.
- Make it possible and practical to specialize it to the platform without the space and speed overhead of what Android has to do.
- Standard libraries (UI, crypto, etc.) are just simple built-in modules.
- Cross-app integration is very easy: it's just plugging into module resolution.
- Run all this on an execution model with formally verified semantics and low memory overhead, for massive security and sandboxing wins without nearly the memory footprint.

This would be incredibly useful for more resource-constrained devices, where you want provable security, but you don't want the overhead that comes with higher level languages and platforms it usually entails. It's also useful for allowing extensive customization of how things work without nearly the pain of tooling, and you could even specialize this to some degree on the device itself, despite it being resource-constrained. (WebAssembly can be streamed to a baseline binary, and most device-specific optimizations don't require large code buffers.)

**Comment by xtuc** [comment]
Sorry for my ignorance, but what's an app bundle?

Also keep in mind that WebAssembly in host independent and is designed to have its API exposed by the host.

**Comment by isiahmeadows** [comment]
> Sorry for my ignorance, but what's an app bundle?

I mean something down the vein of Android's `.apk`.

**Comment by isiahmeadows** [comment]
Closing, since this is a little too close to a business interest I'm exploring...

**Comment by isiahmeadows** [comment]
BTW, if you'd like more context, feel free to DM me [on Twitter](https://twitter.com/isiahmeadows1).
