### ISSUE TITLE
How to run rust code using wasmi?

### ISSUE THREAD

**Issue by AchalaSB** [rustwasm/team#229]
What is command to run code in rust? (wasmi is installed as per https://github.com/paritytech/wasmi)  
Tried ```cargo build --target=wasm32-unknown-unknown```
How can I connect it to web server?
Tried with ```cargo web start --target=wasm32-unknown-unknown ``` but code is not executing.

When I run command ``` cargo run --example=tictactoe```
Getting the message
```Usage: target/debug/examples/tictactoe <x player module> <y player module> ``` 
 But Im not getting how to assign player modules

All helps are appreciated. Thanks in advance

**Comment by Pauan** [comment]
@AchalaSB Why are you using `wasmi`?

Are you just trying to compile Rust code to wasm and then run it?

If so, then you don't need `wasmi` at all, instead you should use one of two options (not both!):

1. Follow the directions for [stdweb](https://crates.io/crates/stdweb).

2. Follow the directions for [wasm-pack](https://rustwasm.github.io/wasm-pack/).

**Comment by fitzgen** [comment]
Thanks for filing an issue.

If your goal is to run wasm on the Web, then wasmi shouldn't come into play. wasmi is for if you want to embed running wasm in your application (say as scripting for a game).

@Pauan's links should provide more guidance. Additionally, you might benefit from going through the game of life tutorial: https://rustwasm.github.io/book/game-of-life/introduction.html

**Comment by AchalaSB** [comment]
@Pauan  Yes. Im trying to run rust code to wasm. As you said tried with stdweb. But code is not running in server ( refer #141)
