### ISSUE TITLE
Use node_modules (Node.js) in WASM ?

### ISSUE THREAD

**Issue by goriunov** [rustwasm/team#232]
The question is pretty much title.

As example suppose i have `node_modules` which creates a WebSocket will say `ws` js is there a way i can pass it to the WASM and use it inside Rust code ? 

And is there a way to pass function from JS to Rust (callback).

Thank you very much :)

**Comment by fitzgen** [comment]
Here are a few links to docs that should help you out:

https://rustwasm.github.io/wasm-bindgen/reference/receiving-js-closures-in-rust.html
https://rustwasm.github.io/wasm-bindgen/examples/closures.html
https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.WebSocket.html

Does this answer your question?

**Comment by goriunov** [comment]
I have went thought links and found `#[wasm_bindgen(module = "./defined-in-js")]` of importing js code, will this work on `node_modules` ? For example :
```
#[wasm_bindgen(module = "crypto")]
```
or 

```
#[wasm_bindgen(module = "https")]
```

**Comment by Pauan** [comment]
@goriunov Yes, it will work.

Also, take a look at [wasm-pack](https://rustwasm.github.io/wasm-pack/), which is a tool that makes it easy to create npm packages with Rust (including importing other npm packages). It internally runs wasm-bindgen.

**Comment by goriunov** [comment]
That is a very good help. Thank you ;) I have also one more question. I have just started with WASM RUST and kind of confused about one thing.

How do i add to external c this kinda thing from js `native.client.group.create(0);` 

I know that `create(0)` can be represented as 

```rust
extern "C" {
  fn create(a: u32) -> JsValue;
}
```

but what if i want to export only `native` from js and then call that long chain. The farthest i went is: 
 
```rust
extern "C" {
// This is completely wrong thing 
 #[wasm_bindgen(js_namespace = native)]
  fn client(a: u32) -> JsValue; 
}
```

I would really appreciate if you could help me this one. Thank you.

**Comment by alexcrichton** [comment]
@goriunov for that you may be intersted in --

* https://rustwasm.github.io/wasm-bindgen/reference/accessing-properties-of-untyped-js-values.html
* https://rustwasm.github.io/wasm-bindgen/reference/working-with-duck-typed-interfaces.html

Does that help?

**Comment by Pauan** [comment]
@alexcrichton I think they're trying to do something like this:

```rust
#[wasm_bindgen]
extern {
    #[wasm_bindgen(js_namespace = "native.client.group")]
    fn create(a: u32) -> JsValue;
}
```

But that doesn't seem to work right now.

**Comment by Pauan** [comment]
@goriunov There might be a better way to do this, but this was the best way that I could come up with:

```rust
#[wasm_bindgen]
extern {
    type Group;

    #[wasm_bindgen(method, getter, structural)]
    fn create(this: &Group, value: u32) -> JsValue;
}

#[wasm_bindgen]
extern {
    type Client;

    #[wasm_bindgen(method, getter, structural)]
    fn group(this: &Client) -> Group;
}

#[wasm_bindgen]
extern {
    type Native;

    #[wasm_bindgen(method, getter, structural)]
    fn client(this: &Native) -> Client;
}

#[wasm_bindgen]
extern {
    static native: Native;
}
```

Here's the example usage in Rust:

```rust
let output = native.client().group().create(5);
```

**Comment by goriunov** [comment]
Would be really good to have 

```rust
#[wasm_bindgen]
extern {
    #[wasm_bindgen(js_namespace = "native.client.group")]
    fn create(a: u32) -> JsValue;
}
```

solution, but second one is alright too :) 
Thank you very much for your help.

**Comment by alexcrichton** [comment]
I'm going to close this as I think it's possible to do so today with wasm-bindgen, and I think https://github.com/rustwasm/rfcs/pull/8 and https://github.com/rustwasm/rfcs/pull/6 also help here quite a lot.
