### ISSUE TITLE
Add an inline_wasm! macro or make inline_asm! work on wasm targets

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#24]
For my use cases, this would have been nice, but not strictly necessary. I expect it will eventually become higher priority for someone.

**Comment by est31** [comment]
Can you explain what this macro should do? Inline assembly in the form of wabt?

**Comment by fitzgen** [comment]
I was imagining writing WAT inline.

**Comment by pepyakin** [comment]
Hm, should be possible with wabt-rs and https://github.com/dtolnay/proc-macro-hack

**Comment by pepyakin** [comment]
Always thought that `js!` works as proc-macro, nice to know!

**Comment by est31** [comment]
@fitzgen I see, that would be quite nice indeed.

> Ideally I think that something like that should be supported by Rust's (currently unstable) asm! though.

The `asm!` macro seems to do *something* on the wasm target, I've only tried out whether compilation errors or we run into llvm assertions or something... nothing of that kind! So maybe it actually is functional already. But generally the intention is I think that the asm syntax is the same over all targets, [see this latest proposal](https://internals.rust-lang.org/t/pre-rfc-inline-assembly/6443).

**Comment by isislovecruft** [comment]
I'd also be interested in inline web assembly as a corollary to what the `test::black_box()` (in libtest) function does, but for wasm32 targets, i.e. as a way to disable optimisations.

**Comment by ashleygwilliams** [comment]
we probably want to track this in a way that's different than an issue on this repo. going to close (but please reopen if i am incorrect and also apologies!)
