### ISSUE TITLE
Dynamic linking experiments are stumbled by unconditional "--export-table"

### ISSUE THREAD

**Issue by pepyakin** [rustwasm/team#251]
I've discovered flags like `--pic`/`--shared` in the latest LLD (seems to be not yet available in the LLD shipped with rust). But when I try to use them I'm getting this LLD error:

``` 
lld: error: -shared/-pie is incompatible with --export-table
```

I tried to pass `--import-table` to override the rustc passed `--export-table`, however, LLD [doesn't support that](https://github.com/llvm-mirror/lld/blob/e3a5e2f228b45f46331d35b2706e2efdfcedd89a/wasm/Driver.cpp#L541), and fails with

```
lld: error: --import-table and --export-table may not be used together
```

Do you have any idea how to proceed here?

**Comment by alexcrichton** [comment]
There's a bit of discussion on the [original PR](https://github.com/rust-lang/rust/pull/53237), and it seems like if LLD doesn't support both flags then we should remove the argument from rustc and require users to pass in an explicit value.

cc @overdrivenpotato

**Comment by pepyakin** [comment]
Oh, the problem might be deeper, since overriding of stack size doesn't seem to work either.

**Comment by alexcrichton** [comment]
I believe the stack size aspect was addressed by https://github.com/rust-lang/rust/pull/57337

**Comment by alexcrichton** [comment]
Should have been fixed in https://github.com/rust-lang/rust/pull/57861, so closing.
