### ISSUE TITLE
Need proper debugging information

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#26]
Source maps only encode source location <--> object code location mappings, and optionally source text content. This doesn't provide for

* recovering scopes, variables, and their current values (for a stepping debugger)

* information about inlined functions (for size profilers and reconstructing the logical stack at any given code location)

* how to format/display values of different types (pointers vs `Box` vs `Vec` etc)

* a way to include a link to an expression evaluator, so the console can be used or conditions can be set on breakpoints

**Comment by est31** [comment]
Related issue: https://github.com/rust-lang/rust/issues/46765

Sooo we'd probably need to come up with an alternative to source maps then that then Firefox and Chrome and other browsers have to implement in their debuggers?

**Comment by fitzgen** [comment]
I think we could mostly adapt DWARF and use bytecode offset rather than pc. DWARF is very flexible.

**Comment by mgattozzi** [comment]
We'd still have to get browsers to support DWARF somehow right?

**Comment by fitzgen** [comment]
> We'd still have to get browsers to support DWARF somehow right?

Two replies:

1. Depending on the tooling, a browser might not be involved at all, so it is more of an ecosystem thing. For example, a size profiler could be run from the command line and get very good info out of DWARF.

2. We can probably get browsers to support DWARF if we push hard enough ;)

**Comment by mgattozzi** [comment]
That's kind of what I was guessing would be the case but just wanted to confirm!

**Comment by alexcrichton** [comment]
Now that we've upgraded LLVM that's actually dwarf info!
