### ISSUE TITLE
Discord link is broken

### ISSUE THREAD

**Issue by sh7dm** [rustwasm/team#270]
### Summary

Discord link given at https://github.com/rustwasm/team/blob/master/README.md#get-involved is broken.

### Additional Details

If I follow it, I can't join clannel

**Comment by drager** [comment]
@sh7dm Hi, thanks for letting us know! This is fixed in #271. You should be able to use this link: https://discord.gg/hBjKfhP

**Comment by sh7dm** [comment]
Thanks
