### ISSUE TITLE
Discord chat link broken

### ISSUE THREAD

**Issue by Apromixately** [rustwasm/team#277]
### Describe the Bug

The link to the Discord chat seems broken.

### Steps to Reproduce

1. Click on the "the #wg-wasm channel of the Rust project's Discord server." on this page https://github.com/rustwasm/team/blob/master/README.md#get-involved

### Expected Behavior

Takes me to a place where I can talk to people...

### Actual Behavior

Takes me to the sad emptiness.

**Comment by Saw-mon-and-Natalie** [comment]
Any updates? 
This is still the case.

**Comment by Apromixately** [comment]
Hmpf...really? There was a PR for this even when I created the issue, iirc.

**Comment by Apromixately** [comment]
@Saw-mon-and-Natalie Now there are two links. But yeah, it's stupid that you have to click two links.

**Comment by Apromixately** [comment]
I just tried and it seems to have gotten even worse. Because now clicking on the link to join the server is not enough, you also have to accept the code of conduct otherwise nothing will work.

**Comment by Saw-mon-and-Natalie** [comment]
@Apromixately, thanks. Just figured it out. At the top of the `README.md`:


<div align="center">

  <h1>Rust + WebAssembly = 💖</h1>

  <strong>A point of coordination for the Rust and WebAssembly Working Group</strong>

  <h3>
    <a href="#get-involved">Get Involved</a>
    <span> | </span>
    <a href="https://discordapp.com/channels/442252698964721669/443151097398296587">Chat</a>
  </h3>
</div>

The `chat` link is confusing. If you have not already joined the `rust` discord server, it points to nothing.
I think it should be changed to something like:

<div align="center">
  <h3>
    <a href="#get-involved">Get Involved</a>
    <span> | </span>
    <a href="https://discordapp.com/invite/rust-lang">Join Discord Server</a>
  </h3>
</div>

or 

<div align="center">
  <h3>
    <a href="#get-involved">Get Involved</a>
    <span> | </span>
    <a href="https://github.com/rustwasm/team#1-join-our-chat">Join Our Chat</a>
  </h3>
</div>
