### ISSUE TITLE
Should we change our recurring WG meeting to every other week?

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#283]
### Should we change our recurring WG meeting from every week to every other week?

I've noticed that our velocity has slowed down a bit and that we haven't had a ton to talk about in the last month or two. I think switching from weekly meetings to every other week makes sense.

What do you think?

+cc @rustwasm/core @rustwasm/book @rustwasm/wasm-pack

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

**Comment by sendilkumarn** [comment]
@fitzgen I do agree. This time is not working out for me greatly, and I keep on missing the meetings.

**Comment by ashleygwilliams** [comment]
sounds like a good idea to me! could also open up time for teams to have team specific meetings, etc

**Comment by MarcAntoine-Arnaud** [comment]
Sounds good, as we want to join soon the meeting, every weeks is too much for us.
We are actually working on a WASM Web player (maybe the first one!) for specific format (ProRes and Jpeg2000 in MXF files...)

**Comment by torch2424** [comment]
@fitzgen Sounds good to me! 😄Doing bi-weekly makes a lot of sense. 

If anyone feels that we should keep weekly, we can do one meeting over chat, and another over video? 🤔 

But again, I think bi-weekly video is the way to go 👍

**Comment by fitzgen** [comment]
Ok, going to switch to every other week. Since we skipped today's meeting (and did a discord chat meeting instead) I've scheduled the next meeting for one week from today: https://github.com/rustwasm/team/issues/284

Thanks for chiming in, everyone!
