### ISSUE TITLE
Unable to Perform Source-Level Debugging of Rust Code in WebAssembly

### ISSUE THREAD

**Issue by slozben** [rustwasm/team#308]
# Unable to Perform Source-Level Debugging of Rust Code in WebAssembly

## Description  
I am unable to perform source-level debugging of Rust code compiled to WebAssembly (Wasm) despite including DWARF debug information and following standard workflows. While the `.wasm` file generated by `cargo build` contains the necessary `.debug_*` sections (as verified using `wasm-objdump`), these sections seem to be stripped or not fully utilized when processed through `wasm-bindgen`. This makes it impossible to step through the original Rust source code in browser developer tools like Chrome and Firefox.

## Steps to Reproduce
1. Create a simple Rust project with WebAssembly bindings using `wasm-bindgen`:
    ```rust
    #[wasm_bindgen]
    pub fn greet() {
        console_log!("Hello, World!");
    }
    ```
2. Compile with debug information:
    ```bash
    cargo build --target wasm32-unknown-unknown
    ```
3. Process the `.wasm` file with `wasm-bindgen`:
    ```bash
    wasm-bindgen target/wasm32-unknown-unknown/debug/<project_name>.wasm --out-dir ./pkg --target web --debug
    ```
4. Serve the generated files (`pkg/`) with a local HTTP server and load them in the browser.
5. Attempt to set breakpoints and step through the Rust source code in Chrome DevTools or Firefox Debugger.

## Expected Behavior  
The browser developer tools should map the WebAssembly module back to the original Rust source code (via DWARF or source maps) and allow stepping through the code.

## Actual Behavior  
- Rust source code does not appear in the browser developer tools.
- Breakpoints cannot be set at the source level.
- `wasm-bindgen` appears to strip or fail to utilize the debug sections from the original `.wasm` file.

## Additional Details
- Debug information is **present** in the `.wasm` file generated by `cargo build`:
    ```bash
    wasm-objdump -x target/wasm32-unknown-unknown/debug/<project_name>.wasm | grep debug
    ```
    Output includes:
    ```
    - name: ".debug_abbrev"
    - name: ".debug_info"
    - name: ".debug_str"
    - name: ".debug_line"
    - name: ".debug_ranges"
    ```
- Debug information is **missing** in the `.wasm` file generated by `wasm-bindgen`:
    ```bash
    wasm-objdump -x pkg/<project_name>_bg.wasm | grep debug
    ```
    No `.debug_*` sections are present.

## Environment
- **Rust Version**: `rustc <1.83.0 (90b35a623 2024-11-26)>`
- **wasm-bindgen Version**: `<wasm-bindgen 0.2.99>`
- **Target**: `wasm32-unknown-unknown`
- **Browser**: Tested on Chrome `< 131.0.6778.205 (Official Build) (arm64)>` and Firefox `<133.0.3 (aarch64)>`

## Impact  
This issue significantly hinders the ability to debug Rust applications compiled to WebAssembly, particularly during development and testing phases. Will pivot to TS if we can't debug from source.

**Comment by CryZe** [comment]
For Chrome at least (not sure about Firefox) you need a browser extension. Did you install that?

**Comment by slozben** [comment]
I installed this extension for chrome
https://chromewebstore.google.com/detail/cc++-devtools-support-dwa/pdcpmagijalfljmkmjngeonclgbbannb

**Comment by CryZe** [comment]
I think you are missing ` --keep-debug` in your wasm-bindgen invokation.

**Comment by slozben** [comment]
I have tried both including this 
wasm-bindgen --target web --debug --keep-debug target/wasm32-unknown-unknown/debug/wasm_hello_world.wasm --out-dir ./pkg

wasm-bindgen guide states the following:
--debug
Generates a bit more JS and Wasm in "debug mode" to help catch programmer errors, but this output isn't intended to be shipped to production.

--keep-debug
When post-processing the .wasm binary, do not strip DWARF debug info custom sections.

Is there a demo that you can point to, where one can run in the browser and step through the source code to see how it should work?

**Comment by CryZe** [comment]
I do not have a small demo, only my large actual application where it works. Maybe you can create a reproduction repository where I can see what the problem is? Cause with `--keep-debug` it should definitely work.

**Comment by slozben** [comment]
@CryZe thank you for the quick replies. It looks like I needed to set path substitutions in the "C/C++ DevTools Support DWARF)" extension. I can now see the directories. It was not related to the compile flags, but to the actual "C/C++ DevTools Support (DWARF)" extension settings related to path substitution.
