### ISSUE TITLE
Tracking issue for node integration

### ISSUE THREAD

**Issue by aturon** [rustwasm/team#37]
Our plan for JS bundlers is to use ES modules to tie everything together, including an outer shim module and an inner .wasm module.

It's unclear how this story will play out in the Node world, which does not (yet?) work with ES modules natively.

**Comment by linclark** [comment]
While there may be some delays based on Node's schedule, I don't expect there to be issues in the long term.

There is experimental support for ES modules in Node at this point. There are [some complications](https://medium.com/@giltayar/native-es-modules-in-nodejs-status-and-future-directions-part-i-ee5ea3001f71) and a somewhat different [proposal from npm](https://gist.github.com/ceejbot/b49f8789b2ab6b09548ccb72813a1054) which may win out, but there's definitely commitment to supporting ES modules.

At TC39, I discussed WASM modules becoming ES modules with the Node TSC director (who is also working on native ES module support) and folks from npm, and there were no concerns about the fact that they would be ES modules.

**Comment by ashleygwilliams** [comment]
for context, much of the shenanigans around the es6 story with modules is about transitioning and/or interoperating with CommonJS. es6 modules should work out of the box with whatever solution they go with, so we should be fine.

**Comment by aturon** [comment]
An early tool: https://github.com/yusinto/node-wasm

**Comment by koute** [comment]
With newest `stdweb` from `master` and the most recent `cargo-web` you can also do this (based on our [hasher example](https://github.com/koute/stdweb/tree/master/examples/hasher)):

```rust
#![feature(proc_macro)]

#[macro_use]
extern crate stdweb;
extern crate sha1;

use stdweb::js_export;
use sha1::Sha1;

#[js_export]
fn sha1( string: &str ) -> String {
    let mut hasher = Sha1::new();
    hasher.update( string.as_bytes() );
    hasher.digest().to_string()
}
```

Then you can do `cargo web build` and load it in Node.js:

```js
const hasher = require( './target/wasm32-unknown-unknown/release/hasher.js' );
console.log( hasher.sha1( "Hello world!" );
```

You could technically take the `.js` and `.wasm` file generated by `cargo-web`, add a `package.json` and easily package it as a normal NPM package.

So, really, while ES6 modules are the future they're hardly necessary *right now*.

**Comment by ashleygwilliams** [comment]
we are tracking this in the individual tool repos, and we have an existing nodejs target that works. closing in favor of tracking this in the tooling repos
