### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by aturon** [rustwasm/team#4]
Talking about "Rust/wasm" or "Rust + wasm" is quite cumbersome. We should consider creating a new brand, along the lines of [Neon] and [Helix].

[Neon]: https://github.com/neon-bindings/neon
[Helix]: http://usehelix.com/

**Comment by steveklabnik** [comment]
My gut says "Rust for the Web"

**Comment by aturon** [comment]
I worry that's also too unwieldy. It'd be nice to have a simple name, I think.

**Comment by est31** [comment]
Yeah "Rust/wasm" doesn't fit well if this project seems to focus on client side javascript. There are non-web embeddings for wasm. In fact I myself play with the thought of creating using wasm in a few non web contexts...

**Comment by badboy** [comment]
@steveklabnik Especially if we want to keep the idea that wasm is not only for the web, that's not perfect (though that's what I've been using as well so far)

**Comment by mgattozzi** [comment]
"Rust for every platform." If the idea is that wasm is a platform independent binary format than it stands that Rust can be on all of them (even when we're not doing wasm). It also leaves it open and vague enough that it can be the web, a client application or tool (both in the browser and on the cli), as well as more exotic locations. "Platform" ends up being what the user wants to interpret it as, whether it's with or without JS.

**Comment by sunfishcode** [comment]
How about "rust.wasm", pronounced "rust dot wasm"?

**Comment by anp** [comment]
If the brand chosen means I can buy a t-shirt with a steampunk spider on it to match my RustConf 1.0 tshirt, I will be even more excited about rust/wasm. *Web*Assembly, after all.

Or maybe a horrifying steampunk spider crab hybrid.

Anyways regardless of naming the initiative, Ferris should definitely have a super badass spider sister as part of this.

Sorry if I'm crashing a party here!

**Comment by killercup** [comment]
So, 2017 me would say _WebOxide_, but I [heard](https://www.reddit.com/r/rust/comments/7kjdiq/faster_030_released_the_simd_library_for_humans/drfac8r/?context=1) in 2018 we should name stuff after cities…

**Comment by est31** [comment]
I'm not entirely sure what this project itself is about. Is it mainly about web related wasm? Then I think it is better to make the name web specific. Some of the issues seem very web related to me, that's why I wonder.

**Comment by aturon** [comment]
@est31 It's not tied to the web, no. It's meant to cover all things at the intersection of Rust and wasm. Today, though, that's almost entirely connected to JS host environments, so a lot of the work is going to focus there. But e.g. wasm-gc is not tied to JS/web in any way.

**Comment by alexcrichton** [comment]
I think we've settled quite a bit since this was first opened, so closing!
