### ISSUE TITLE
Generate wasm -sys crates from webidl

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/team#66]
@alexcrichton said wasm-bindgen might be able to do this one day.

https://heycam.github.io/webidl/

**Comment by Diggsey** [comment]
I already do this quite successfully for WebGL: https://github.com/brendanzab/gl-rs/pull/447

**Comment by alexcrichton** [comment]
Certainly! I believe there are multiple methods of binding to JS apis in wasm right now with wasm-bindgen being one of the options, I do plan to imement webidl generation of apis for binding the web platform for sure!

**Comment by alexcrichton** [comment]
I've opened an issue for this [dedicated to wasm-bindgen](https://github.com/alexcrichton/wasm-bindgen/issues/42) as well

**Comment by fitzgen** [comment]
Closing this since we have a dedicated issue in wasm-bindgen and ongoing implementation work there.
