### ISSUE TITLE
Document workflows

### ISSUE THREAD

**Issue by aturon** [rustwasm/team#7]
Ideally this repo would contain some additional markdown documents giving our current "best practice workflows", e.g. including running `wasm-gc` and other tools.

**Comment by aturon** [comment]
This could maybe start as just `workflows.md` organically collecting common workflows. cc @alexcrichton

**Comment by mgattozzi** [comment]
Would we want to do something that could also be put into a book much like TRPL and the nomicon?

**Comment by alexcrichton** [comment]
Sounds good to me! I've started this in https://github.com/aturon/rust-wasm/pull/9 and would be up for any organization whatsoever :)

**Comment by jrichocean** [comment]
This issue has been moved [here](https://github.com/rustwasm/book/issues/22)
