### ISSUE TITLE
Tracking issue for javascript bundler integration

### ISSUE THREAD

**Issue by aturon** [rustwasm/team#8]
This is a point of coordination for work that JS bundlers are doing along two fronts:

- Consuming npm packages with .wasm binaries.
- Allowing for *direct* use of Rust source.

The former is connected to our [npm integration story](https://github.com/aturon/rust-wasm/issues/5#issuecomment-357397585), but will probably *not* be Rust-specific, since the npm packages will likely just contain a compiled .wasm blob.

**Comment by steveklabnik** [comment]
(changed the title because I thought this was about ruby's Bundler, not the generic idea of a "bundler")

**Comment by linclark** [comment]
I've added a diagram of the toolchain in https://github.com/aturon/rust-wasm/issues/5#issuecomment-357397585 which includes bundlers.

**Comment by aturon** [comment]
Relevant work: https://github.com/glimmerjs/broccoli-rust2wasm

**Comment by mgattozzi** [comment]
Relevant: Parcel another web bundler just added support to drop in `.rs` files to get `wasm`. See the release announcement [here](https://medium.com/@devongovett/parcel-v1-5-0-released-source-maps-webassembly-rust-and-more-3a6385e43b95). If we haven't already we should reach out and see how they did it, what the pain points were, and what can be done to help.

**Comment by aturon** [comment]
Update: we met with the Parcel team and had a great discussion! 

The main focus was on how we ultimately want to support Rust *libraries* getting pulled in. The short story is: 

We should be able to publish an npm package that has:

- an outer ES module written in JS, generated by wasm-bindgen, that works with JS-friendly types
- an "inner" module, which is a .wasm file, that fully specifies its imports (giving both module and function names; see [the ABI issue](https://github.com/rust-lang-nursery/rust-wasm/issues/29))

The bundler is set up to allow you to import from .wasm files as if they were ES modules, so it will natively understand what's going on, and generate the appropriate code to instantiate the .wasm module. Parcel does not yet support imports from .wasm modules, but they will start working on that now.

Note that this model is not in any way tied to Rust. In particular, the wasm-bindgen tool is ultimately intended to be language-agnostic.

We intend to chat again with Webpack to see whether they are following a similar plan.

**Comment by alexcrichton** [comment]
I've updated [wasm-bindgen](https://github.com/alexcrichton/wasm-bindgen) with the results of the discussion ("everything is an ES6 module") and it's got some examples about how it all works!

> The bundler is set up to allow you to import from .wasm files as if they were ES modules, so it will natively understand what's going on, and generate the appropriate code to instantiate the .wasm module.

Another point to add to this is that we're expecting bundlers will also resolve the imports of a wasm file itself as if it were an ES6 module. In that sense the bundler is the one that's ultimately responsible for resolving the wasm modules imports (in addition to instantiation)

**Comment by alexcrichton** [comment]
Webpack 4.0 beta supports wasm modules natively, and the README of wasm-bindgen was rewritten to exercise this like [`hello_world` example](https://github.com/alexcrichton/wasm-bindgen/tree/master/examples/hello_world)

**Comment by alexcrichton** [comment]
I'm gonna close this since webpack works quite well nowadays!
