### ISSUE TITLE
Link to Lin's overview article

### ISSUE THREAD

**Issue by aturon** [rustwasm/team#90]
Just wanted to note that https://hacks.mozilla.org/2018/03/making-webassembly-better-for-rust-for-all-languages/ provides a pretty nice overview of the efforts here, and will be followed up by further posts on each of the pieces. It'd be good to find a spot to get this content in front of people!

**Comment by sendilkumarn** [comment]
@aturon https://github.com/rust-lang-nursery/rust-wasm/issues/79#issuecomment-373107119 :)

**Comment by mgattozzi** [comment]
Let's get it in the README then. I think it'll be a good spot for it

**Comment by alexcrichton** [comment]
I'm gonna close this as it's done in the news thread!
