### ISSUE TITLE
Executable wasm files on Linux

### ISSUE THREAD

**Issue by mgattozzi** [rustwasm/team#91]
I managed to get [wasm files as executables on Linux](https://twitter.com/mgattozzi/status/974810805043679233). I'll do a blog post and write up more about it later, but now it's possible so it would be interesting to see what we can do to explore this space even more.

**Comment by mgattozzi** [comment]
@pepyakin I ended up using wasmi for this to invoke a binary file's "main" function. I've been trying to pass memory addresses such as strings across boundaries in order to print stuff out but that segfaults so all I can send back is numbers. I'm wondering if this is either a limitation of the interpreter or the environment? I'm not really sure but it would be cool if we could get println to actually work.

**Comment by pepyakin** [comment]
@mgattozzi That sounds as something possible for me, so I think that I misunderstood you. Can you give me an example? Share the code?

**Comment by mgattozzi** [comment]
@pepyakin I'm going to do a write up today and post the code with a more detailed explanation! I'll ping you when I have it done

**Comment by xtuc** [comment]
I'm interested in this too, could you please post it here?

**Comment by mgattozzi** [comment]
That is the plan! Mostly want to coordinate around this because there's some things that kind of tie into #16

**Comment by ashleygwilliams** [comment]
i'm not certain that this thread is the right place/way to track this. i think new wasm runtimes can be brought up in the News issue. currently a wasm runtime is not on this working group's roadmap. if/when it is, we'll find a place for this convo.
